---
title: "spideys"
author: "Carla"
date: "2023-05-24"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 9, fig.height = 5, dpi = 500,
                      retina = 1, fig.showtext = TRUE, layout = "l-page")
```

```{r packages}

rm(list=ls())
library(tidyverse)
library(sf)
library(rnaturalearth)
library(rmapshaper)
library(scico)
library(here)
library(elevatr)
library(mapview)


theme_set(theme_void(base_family = "TrebuchetMS", base_size = 11))
theme_update(
  legend.position = "top",
  legend.spacing = unit(2, "lines"),
  legend.title = element_text(face = "bold")
)
```


# Data

```{r data}
## import spider data 
spiders <- read.csv("C:/Users/carla/Documents/Lincoln Uni/ECOL609/Spiders/spiders_ecol_609/spiders.csv", sep =",",dec=".")

df_coords <- spiders

df_coords <- df_coords %>% 
na.omit()

head(df_coords)
summary(df_coords)

# Create a smaller dataframe with 4 necessary columns

df_spideys <- df_coords %>% dplyr::select('longitude','latitude', 'taxon_family_name', 'id')

summary(df_spideys)

# Create dataframe with only spatial data
df_spidey_coords <- df_coords %>% dplyr::select('longitude','latitude')

# Set projection

spid_prj <- "EPSG:4326"

# Extract elevation from lat and long data
elevation <- get_elev_point(df_spidey_coords,prj= spid_prj, src = c("aws"))

summary(elevation)


# set crs 
sf_countries <- 
  ne_download(scale = 50, returnclass = "sf") %>% 
  st_transform(crs = "+proj=moll +R=10567000 +lon_0=0 +x_0=0 +y_0=0 +units=m +towgs84=0,0,0,0,0,0,0 +no_defs")


spidey_coords <- 
  df_spideys %>% 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
  st_transform(crs = st_crs(sf_countries))


# turn dataframe into a spatial points data frame (not needed)
#spidey_final <- sf::as_Spatial(spidey_coords, cast = TRUE, IDs = paste0("id"))

#summary(spidey_final)

# Transform elevation data to data frame  

df_elev = as(elevation, "data.frame") 
summary(df_elev)

df_elev2 <- df_elev %>%
  rename(longitude=coords.x1,latitude=coords.x2)

ID <- c(1:87)

df_elev2$ID <-ID

df_spideys$ID <-ID

# Merge both data frames 

df_combined <- df_spideys %>%
 left_join(df_elev2, by="ID") %>%
  dplyr::select(-c(longitude.y, latitude.y,id)) %>%
  rename(longitude=longitude.x, latitude=latitude.x) %>%
  mutate(elevation=as.numeric(elevation)) 

summary(df_combined)
print(df_combined)

# remove nas

df_coords2 <- df_combined %>% 
  mutate_all(na_if,"") %>%
  na.omit()


# Save dataframe as csv 

write.csv(df_combined,"C:/Users/carla/Documents/Lincoln Uni/ECOL609/Spiders/spiders_ecol_609/combined.csv")

write.csv2(df_combined,"C:/Users/carla/Documents/Lincoln Uni/ECOL609/Spiders/spiders_ecol_609/combined2.csv")

## turn review locations into spatial objects
sf_coords <- 
  df_coords %>% 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
  st_transform(crs = st_crs(sf_countries))

# Look at data on map
mapview(sf_coords, xcol = "longitude", ycol = "latitude", crs = 4326, grid = FALSE)


# Number of individuals per family
table(df_combined$taxon_family_name)

df_species<- aggregate(taxon_family_name ~ elevation, data =df_combined, function(x) length(x))
```

``` {r Plot on map}
# Plot number of families at each elevation 
sf_borders <- rmapshaper::ms_innerlines(sf_countries)

sf_oceans <- 
  ne_download(category = "physical", type = "ocean", scale = 50, returnclass = "sf") %>% 
  st_transform(crs = st_crs(sf_countries))

sf_graticules <- 
  ne_download(category = "physical", type = "graticules_30", scale = 50, returnclass = "sf") %>% 
  st_transform(crs = st_crs(sf_countries))

## turn review locations into spatial objects
sf_coords <- 
  df_coords2 %>% 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
  st_transform(crs = st_crs(sf_countries))

````

````{r add layers}

# Create basemap
base_map <- 
  ggplot() + 
  geom_sf(data = sf_oceans, fill = "#d8e5f0", color = "#d8e5f0", size = .15) +
  geom_sf(data = sf_countries, fill = "#ded6c2", color = "#ded6c2", size = .15) +
  geom_sf(data = sf_graticules, color = "white", size = .1) +
  geom_sf(data = sf_countries, fill = "#ded6c2", color = "transparent", size = .01) +
  geom_sf(data = sf_borders, color = "#e5ddc6", size = .15) 


# Add layers by categories
world_map <-base_map + 
  geom_sf(
    data = sf_coords, aes(shape = taxon_family_name), 
    size = 1.3, color = "white"
  )+ 
  geom_sf(
    data = sf_coords, aes(shape = taxon_family_name, fill = elevation), 
    size = 1.1, stroke = .3
  ) +

  scale_fill_viridis_c(
    option = "A", direction = -1, end = .9, name = "Elevation (m)", 
    guide = guide_colorsteps(
      barwidth = unit(11, "lines"), barheight = unit(.5, "lines"),
      title.position = "top", order = 1, show.limits = TRUE
    )
  ) +
  scale_shape_manual(
    values = c(1,2,3,4,5,6,7,8,9,10,21,23), name = "Family", labels=c ("1","2","3","4","5","6","7","8","9","10","11", "12"),
    guide = guide_legend(title.position = "top", order = 2,
                         override.aes = list(fill = "#289689", size = 4))
  ) 


# Zoom in on New Zealand
zoom_map <- world_map

head(zoom_map)

zoom_map + coord_sf(xlim =c() )

st_crs(sf_coords)
```

# Linear models
lm <- lm(elevation~taxon_family_name, data=df_combined)
plot(lm)
summary(lm)

```